from beartype import BeartypeConf
from beartype.claw import beartype_this_package

conf = BeartypeConf(
    is_color=True,
    is_debug=False,
    is_pep484_tower=True,
    violation_type=TypeError,
)

beartype_this_package(conf=conf)

from .adev import (  # noqa: E402
    Dual,
    categorical_enum_parallel,
    expectation,
    flip_enum,
    flip_enum_parallel,
    flip_mvd,
    flip_reinforce,
    geometric_reinforce,
    normal_reinforce,
    normal_reparam,
    multivariate_normal_reparam,
    multivariate_normal_reinforce,
)
from .core import (  # noqa: E402
    GFI,
    Distribution,
    Fn,
    Pytree,
    Const,
    const,
    Trace,
    Vmap,
    Scan,
    Cond,
    gen,
    get_choices,
    tfp_distribution,
    trace,
    sel,
    Selection,
)
from .pjax import (  # noqa: E402
    modular_vmap,
    seed,
)
from .distributions import (  # noqa: E402
    bernoulli,
    beta,
    categorical,
    flip,
    normal,
    uniform,
    exponential,
    poisson,
    multivariate_normal,
)
from .mcmc import (  # noqa: E402
    MCMCResult,
    metropolis_hastings,
)
from .smc import (  # noqa: E402
    ParticleCollection,
    init,
    change,
    extend,
    rejuvenate,
    resample,
)

__all__ = [
    "GFI",
    "Distribution",
    "Dual",
    "Fn",
    "Pytree",
    "Const",
    "const",
    "Trace",
    "Vmap",
    "Scan",
    "Cond",
    "bernoulli",
    "beta",
    "uniform",
    "exponential",
    "poisson",
    "categorical",
    "categorical_enum_parallel",
    "expectation",
    "flip",
    "flip_enum",
    "flip_enum_parallel",
    "flip_mvd",
    "flip_reinforce",
    "gen",
    "geometric_reinforce",
    "get_choices",
    "MCMCResult",
    "metropolis_hastings",
    "modular_vmap",
    "normal",
    "normal_reinforce",
    "normal_reparam",
    "multivariate_normal",
    "multivariate_normal_reparam",
    "multivariate_normal_reinforce",
    "seed",
    "sel",
    "Selection",
    "tfp_distribution",
    "trace",
    "ParticleCollection",
    "init",
    "change",
    "extend",
    "rejuvenate",
    "resample",
]
